#!/bin/bash
clear
cd $HOME 
#########
# COLORS
#########

#colors
#colors
white="\033[1;37m"                                          ##
grey="\033[0;37m"                                           ##
purple="\033[1;35m"                                         ##
red="\033[1;31m"                                            ##
green="\033[1;32m"                                          ##
yellow="\033[1;33m"                                         ##
purple="\033[0;35m"                                         ##
cyan="\033[0;36m"                                           ##
cyan1="\033[1;36m"                                          ##
cafe="\033[0;33m"                                           ##
fiuscha="\033[0;35m"                                        ##
blue="\033[1;34m"                                           ##
l_red="\033[1;37;41m"                                       ##
nc="\033[0m"                                                ## 

arch=`uname -m`
ArNam=$(dpkg --print-architecture)
#spinner
spinner() {
        pid=$!
        spin='\|/-'
        i=0
        tput civis
        while kill -0 $pid 2>/dev/null
	do
                i=$(( (i+1) %4 ))
                printf "\r${cyan1}[${spin:$i:1}]${nc} ${cyan1} $launch"
                sleep .1
	done
        printf "\r   ${green}[✔]${nc} ${green} $splashdown";echo
        tput cnorm
}
function os () {
	cat /etc/os-release > /dev/null 2>&1
	if [ "$?" -eq "0" ]; then
		OS=DEBIAN 
		BIN="/usr/bin"
		main="/usr/share/shark"
                sudo apt install iputils-ping -y &>/dev/null
		sudo apt install p7zip-full -y &>/dev/null
	else
		OS=TERMUX
		BIN="/usr/local/bin"
		main="/usr/local/share/shark"
                #brew ncurses-utils -y &>/dev/null
                brew install p7zip -y &>/dev/null
	fi
}

function git_clone() {
	launch="cloning shark";splashdown="shark cloned";echo
	[ -d "${main}" ] && rm -rf ${main} > /dev/null 2>&1
	(git clone https://github.com/E343IO/sharkmac --quiet ${main} --depth=1) & spinner
}


function dependencies() {
killall -q dpkg apt pkg &>/dev/null
clear
sleep 1
     launch="installing lib";splashdown="installed lib"; echo
	for i in apache2 php jq curl git unzip dialog pacman proot dpkg; do					
    		if [ ${OS} != "DEBIAN" ]; then	
    			(brew update -y &> /dev/null && brew install ${i} -y &> /dev/null && brew install proot resolv-conf &> /dev/null)& spinner
		else
			(sudo apt-get install ${i} -y &> /dev/null && sudo dnf -y install &> /dev/null)& spinner
		fi
	done
}

function setup_cloudflare() {
          launch="Installing server1";splashdown="installed.";echo
	  (brew install cloudflare/cloudflare/cloudflared &> /dev/null)& spinner
}

function final_touchup() {
	for i in shark; do
		chmod +x ${main}/${i}
		mv ${main}/${i} ${BIN}
		launch="setting up files"; splashdown="done";echo
		(cd ${main} && 7z x file &>/dev/null)& spinner

	done
        printf "\n${green}>>${white} simply run : sharkmac \n\n ${nc}"
}
printf "${yellow}Please Wait.\n\n[!] Don't terminate this task.\n"
os
clear
printf "${green}Setting up libs...\n"
sleep 2
clear
dependencies
git_clone
setup_cloudflare
final_touchup

#####################################
#       DON'T TRY TO COPY 😂😂     #
#   JUST LEARNING KEEP SUPPORTING   #
#             THANKYOU              #
#####################################
